name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Gera todo dia à meia-noite
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Generate Snake SVG
        uses: Platane/snk@v2
        with:
          github_user_name: Gabez19
          outputs: |
            ./output/github-contribution-grid-snake.svg

      - name: Commit and Push
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Generated snake animation"
          git push
